In [1]:
import numpy as np
import torch

In [2]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2array = torch_data.numpy()

In [3]:
print(np_data)
print(torch_data)
print(tensor2array)

[[0 1 2]
 [3 4 5]]

 0  1  2
 3  4  5
[torch.LongTensor of size 2x3]

[[0 1 2]
 [3 4 5]]


In [4]:
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(np.abs(data))
print(torch.abs(tensor))

[1 2 1 2]

 1
 2
 1
 2
[torch.FloatTensor of size 4]



In [5]:
print(np.mean(data))
print(torch.mean(tensor))

0.0
0.0


In [6]:
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)
print(np.matmul(data, data))
print(torch.mm(tensor, tensor))

[[ 7 10]
 [15 22]]

  7  10
 15  22
[torch.FloatTensor of size 2x2]



In [7]:
data = np.array(data)
tensor = torch.from_numpy(data)
print(data.dot(data))
print(tensor.dot(tensor))

[[ 7 10]
 [15 22]]
30
